[package]
name = "pikpak_core"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
