/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: booiris02@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResp
 */
export interface BaseResp {
    /**
     * 
     * @type {number}
     * @memberof BaseResp
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResp
     */
    message: string;
}

/**
 * Check if a given object implements the BaseResp interface.
 */
export function instanceOfBaseResp(value: object): value is BaseResp {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function BaseRespFromJSON(json: any): BaseResp {
    return BaseRespFromJSONTyped(json, false);
}

export function BaseRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResp {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
    };
}

export function BaseRespToJSON(value?: BaseResp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
    };
}

