name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  backend:
    name: Backend

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: --deny warnings

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain Components
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --all

      - name: Clippy
        run: cargo clippy --all

      - name: Format
        run: cargo fmt --all --check

  frontend:
    name: Frontend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: CD
        run: cd website

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
